method: bayes   #Available options : [grid, random, bayes]
entity: benchmark-nlp 
project: bayes_lr
metric:
    #Metric is only relevant for bayesian search
    name: f1_macro
    goal: maximize

parameters: 
    #Describe parameters here
    C:
        values: [0.001, 0.01, 0.1, 1, 10, 100, 1000]
    penalty:
        value: l2
    solver:
        value: lbfgs
    random_state:
        value: 42
    class_weights:
        value: 'balanced'

