method: random   #Available options : [grid, random, bayes]
entity: benchmark-nlp 
project: hyperopt
metric:
    #Metric is only relevant for bayesian search
    name: loss
    goal: minimize

parameters: 
    #Describe parameters here
    C:
        min: 0
        max: 10
        distribution: uniform   #Many distributions available : https://docs.wandb.ai/guides/sweeps/configuration#distribution 
    penalty:
        value: l2
    solver:
        value: lbfgs
    random_state:
        value: 42

