method: bayes   #Available options : [grid, random, bayes]
entity: benchmark-nlp 
project: hyperopt
metric:
    #Metric is only relevant for bayesian search
    name: f1_macro
    goal: maximize

parameters: 
    #Describe parameters here : https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC
    C:
        values: [0.001, 0.01, 0.1, 1, 10, 100, 1000]    
    kernel:
        value: 'linear'
    class_weights:
        value: 'balanced'
    random_state:
        value: 42
early_terminate:
    type: hyperband
    min_iter: 1
