method: random   #Available options : [grid, random, bayes]
entity: benchmark-nlp 
project: hyperopt
metric:
    #Metric is only relevant for bayesian search
    name: loss
    goal: minimize

parameters: 
    #Describe parameters here : https://xgboost.readthedocs.io/en/stable/parameter.html
    
    gamma:
        min: 0
        max: 1
        distribution: uniform
    n_estimators:
        min: 10
        max: 150
        distribution: int_uniform
    learning_rate:
        min: 0.001
        max: 0.1
        distribution: uniform
    max_depth:
        min: 0
        max: 10
        distribution: int_uniform    
    random_state:
        value: 42

