method: random   #Available options : [grid, random, bayes]
entity: benchmark-nlp 
project: hyperopt
metric:
    #Metric is only relevant for bayesian search
    name: loss
    goal: minimize

parameters: 
    #Describe parameters here : https://xgboost.readthedocs.io/en/stable/parameter.html
    
    eta:
        min: 0    
        max: 1
        distribution: uniform   #Many distributions available : https://docs.wandb.ai/guides/sweeps/configuration#distribution
    booster:
        values: ['gbtree','gblinear','dart']
    gamma:
        min: 0
        max: # tbd
        distribution: #tbd
    n_estimators:
        min: 10
        max: #
        distribution: int_uniform
    learning_rate:
        min: 0.001
        max: 0.1
        distribution: uniform
    max_depth:
        min: 0
        max: #tbd
        distribution: int_uniform    
    random_state:
        value: 42

