method: bayes   #Available options : [grid, random, bayes]
entity: benchmark-nlp 
project: hyperopt
metric:
    #Metric is only relevant for bayesian search
    name: f1_macro
    goal: maximize

parameters: 
    #Describe parameters here : https://xgboost.readthedocs.io/en/stable/parameter.html
    learning_rate:
        values: [0.0001, 0.001,0.01,0.1]
    gamma:
        min: 1
        max: 10
        distribution: uniform
    max_depth:
        min: 3
        max: 7
        distribution: int_uniform
    n_estimators:
        values: [10,100, 1000,10000]
    colsample_bytree:
        min: 0.1
        max: 1
        distribution: uniform
    random_state:
        value: 42
early_terminate:
    type: hyperband
    min_iter: 1


